### ISSUE TITLE
Save and Sync button - HTTP ERROR 500

### ISSUE THREAD

**Issue by davidbrowaeys** [Neuralab/WooCommerce-Salesforce-integration#9]
Hi there, 

We did install this plugin. We are able to connect and create the fields mapping but when we click on **Save and Sync** button on an order we are getting the following error:  

_This page isn’t working

magasales.com is currently unable to handle this request.
HTTP ERROR 500_

**Comment by BPMUK** [comment]
Having the same issue here - did you get anywhere?

**Comment by andreafdaf** [comment]
having the same issue, the error printed to the logs is the following:
```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function read() on null in /var/www/test-ecommerce/wp-content/plugins/woocommerce/includes/legacy/abstract-wc-legacy-order.php:628
Stack trace:
#0 /var/www/test-ecommerce/wp-content/plugins/WooCommerce-Salesforce-integration-master/includes/models/class-nwsi-order-model.php(23): WC_Abstract_Legacy_Order->init(1639)
#1 /var/www/test-ecommerce/wp-content/plugins/WooCommerce-Salesforce-integration-master/includes/controllers/core/class-nwsi-salesforce-worker.php(80): NWSI_Order_Model->__construct(1639)
#2 /var/www/test-ecommerce/wp-content/plugins/WooCommerce-Salesforce-integration-master/includes/views/class-nwsi-orders-view.php(45): NWSI_Salesforce_Worker->handle_order(1639)
#3 /var/www/test-ecommerce/wp-includes/class-wp-hook.php(300): NWSI_Orders_View->process_order_sync_request(1639)
#4 /var/www/test-ecommerce/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/test-ecommerce/wp-includes/plugin.php(453): WP_H" while reading response header from upstream
```

**Comment by Marceswan** [comment]
I am encountering this issue as well, HTTP Error 500.

**Comment by skynixukraine** [comment]
Hello,

It still does not work. Is there any planned fix in the nearest feature?

**Comment by matejbasic** [comment]
Same as issue #12.
Should be fixed with https://github.com/Neuralab/WooCommerce-Salesforce-integration/commit/6d68c166ca073711da0627e19bc8dadad4226b38 commit.
